### ISSUE TITLE
Borrowing violation due to writing through read-only pointer.

### ISSUE THREAD

**Issue by icmccorm** [wisbery/dec-number-sys#1]
I've been developing an experimental version of Miri that can execute foreign functions by interpreting LLVM bytecode. I was testing it on this crate, and it found a borrowing violation in the test `test_dec_quad_get_coefficient`. 

This seems to be caused by the implementation of `dec_quad_get_coefficient`, which passes an immutable pointer to `bcd` into the function `decQuadGetCoefficient`.
```
pub fn dec_quad_get_coefficient(x: &DecQuad, bcd: &[u8; DEC_QUAD_PMAX]) -> c_int {
  unsafe { decQuadGetCoefficient(x, bcd.as_ptr()) }
}
```
However, `decQuadGetCoefficient` attempts to mutate through this pointer at line 1061 of [decCommon.c](https://github.com/wisbery/dec-number-sys/blob/main/decNumber-icu-368/decCommon.c), in the implementation of `decFloatGetCoefficient`. At this point, `bcdar` is an alias for `bcd`. 
```
GETCOEFF(df, bcdar);
```
The macro GETCOEFF expands to the following, in which `bcdar` is mutated:
```
uInt sourhi=DFWORD(df, 0);                        
*(bcdar)=(uByte)DECCOMBMSD[sourhi>>26];              
dpd2bcd8(bcdar+1, sourhi>>10);                       
dpd2bcd83(bcdar+4, sourhi);}
```

**Comment by ghost** [comment]
@icmccorm Thanks for pointing this out!
